services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
  client:
    depends_on:
      - server
    build:
      context: .
    entrypoint: "/website"
    ports:
      - 3000:3000
    environment:
      SERVER_HOST: 'http://host.docker.internal:8080'